import { loadSource } from "@tpm/adapters";
import { createMemorySink, fingerprint, selectBaseline, calibrateHealth, healthGate, defaultThresholds } from "@tpm/core";
import { Session } from "node:inspector/promises";
import { writeFileSync } from "node:fs";
const source = await loadSource(process.argv[2] ?? "te_process.csv");
const grid = source.grid;
const sink = createMemorySink("prof0001");
const fps = grid.values.map((x) => fingerprint(x, grid.episodes));
const base = selectBaseline(grid, fps, sink);
console.log("baseline", JSON.stringify(base.value.window));
const session = new Session();
session.connect();
await session.post("Profiler.enable");
await session.post("Profiler.start");
let t = performance.now();
const cal = calibrateHealth(grid, base.value.window, fps, sink, 42);
console.log("calibrateHealth ms", (performance.now() - t).toFixed(0), JSON.stringify(cal.thresholds));
t = performance.now();
const health = healthGate(grid, base.value.window, fps, { ...defaultThresholds, ...cal.thresholds }, sink);
console.log("healthGate ms", (performance.now() - t).toFixed(0), health.filter((h) => h.value.health !== "healthy").length, "failed");
const { profile } = await session.post("Profiler.stop");
writeFileSync(process.argv[3] ?? "calib.cpuprofile", JSON.stringify(profile));
